export const participantes = [
    { dni: "47042298", nombres: "MIRIANN ARELY SANCHEZ CHAVEZ", certificado:"reposteria.pdf" },
    { dni: "71338215", nombres: "MARILYN YARALDI VILLANUEVA ESPEJO", certificado:"reposteria.pdf" },
    { dni: "46901654", nombres: "FLOR MARIANA RAMIREZ ROSARIO", certificado:"reposteria.pdf" },
    { dni: "42372968", nombres: "SARITA HAYDÉE REYES BENITES", certificado:"reposteria.pdf" },
    { dni: "44382616", nombres: "ELICIA RAMIREZ CUSTODIO", certificado:"reposteria.pdf" },
    { dni: "71338223", nombres: "NILDA JULISSA TORIBIO BRICEÑO", certificado:"pescados_mariscos.pdf" },
    { dni: "47510951", nombres: "NEYDA  MILENY TORIBIO BRICEÑO", certificado:"pescados_mariscos.pdf" },
    { dni: "42756199", nombres: "MARTHA BETZABETH RODRÍGUEZ DÍAZ", certificado:"pescados_mariscos.pdf" },
    { dni: "71804505", nombres: "NANCY ZULEMA ALVA TIRADO", certificado:"reposteria.pdf" },
    { dni: "71228184", nombres: "DIANA ELVIRA ALIAGA GALLARDO", certificado:"AI-BVL.pdf" },
    { dni: "73186760", nombres: "MARILÚ ISAMAR RIOJAS BURGA", certificado:"AI-BVL.pdf" },
    { dni: "75088745", nombres: "RODRÍGUEZ CABELLOS YHENY YASMIN", certificado:"AI-BVL.pdf" },
    { dni: "70174983", nombres: "DIEGO ANTONIO ESPINO VEJARANO", certificado:"AI-BVL.pdf" },
    { dni: "74904159", nombres: "LOZANO COTRINA FRANK JEANPIERRE", certificado:"AI-BVL.pdf" },
    { dni: "74651507", nombres: "LICELY YONALY MANOSALVA CAMPOS", certificado:"AI-BVL.pdf" },
    { dni: "45372353", nombres: "ROSARIO DEL PILAR HEREDIA OLIVERA", certificado:"AI-BVL.pdf" },
    { dni: "73512520", nombres: "GABRIELA KATHERINE MICHILOT HUACHILLO", certificado:"AI-BVL.pdf" },
    { dni: "45694656", nombres: "KATTY GISSELA REYES VELÁSQUEZ", certificado:"AI-BVL.pdf" },
    { dni: "72910613", nombres: "BURGA DELGADO CRISTIAN MAYCOL", certificado:"AI-BVL.pdf" },
    { dni: "17860294", nombres: "VICTORIA HAYDEÉ VEJARANO GARCÍA", certificado:"AI-BVL.pdf" },
    { dni: "72772441", nombres: "JHENNY LISBETH VÁSQUEZ HUAMAN", certificado:"AI-BVL.pdf" },
    { dni: "71480130", nombres: "CORACY MINERVA SAENZ ANTONIO", certificado:"AI-BVL.pdf" },
    { dni: "72513092", nombres: "SANDRA MILAGROS PASTOR IZQUIERDO", certificado:"AI-BVL.pdf" },
    { dni: "73102690", nombres: "MELANI NICOL RODRIGUEZ JAIMES", certificado:"AI-BVL.pdf" },
    { dni: "72214050", nombres: "SOFÍA YENNIFER MORALES SÁNCHEZ", certificado:"AI-BVL.pdf" },
    { dni: "70200660", nombres: "SILVIA MERCEDES CUBA FERNANDEZ", certificado:"AI-BVL.pdf" },
    { dni: "70134421", nombres: "ADELI GRIMANESA MARIN ESPINOLA", certificado:"AI-BVL.pdf" },
    { dni: "72740259", nombres: "NELI ALEJANDRINA QUIROZ BADA", certificado:"reposteria.pdf" },
    { dni: "74292387", nombres: "CÉSAR PERCY SANTOS TORRES", certificado:"pescados_mariscos.pdf" },
    { dni: "71338223", nombres: "NILDA JULISSA TORIBIO BRICEÑO", certificado:"bartender.pdf" },
    { dni: "46767121", nombres: "DIANE EMELYT VÁSQUEZ MONSEFÚ", certificado:"bartender.pdf" },
    { dni: "41716165", nombres: "SANDERS WIDMARK SÁNCHEZ CONTRERAS", certificado:"bartender.pdf" },
     { dni: "74292387", nombres: "CÉSAR PERCY SANTOS TORRES", certificado:"bartender.pdf" },
    { dni: "44278145", nombres: "LILIAN ESTHER CASTAÑEDA VILLAVICENCIO", certificado:"reposteria.pdf" },
];
