export const participantes = [
{ dni: "20250901", nombres:"ROJAS GUTIERREZ SANDRA JACQUELINE", certificado:"UNIAS1.pdf" },
{ dni: "76452190", nombres:"SHARON JHOSELINE PAREDES CONDORI", certificado:"CERSTAT.pdf" },
{ dni: "75995662", nombres:"EVONNY CONNIE SOBERON MELGAR", certificado:"CERSTAT.pdf" },
{ dni: "60782729", nombres:"JESSAIDY MAIALEN QUICAÑO CHIRINOS", certificado:"CERSTAT.pdf" },
{ dni: "73485601", nombres:"NAYELI YURNETH QUISPE ESPINOZA", certificado:"CERSTAT.pdf" },
{ dni: "73856021", nombres:"DORA LETICIA SURCO MACHACCA", certificado:"CERSTAT.pdf" },
{ dni: "76227342", nombres:"SANDRA YULEMI DÍAZ QUISPE", certificado:"CERSTAT.pdf" },
{ dni: "20250902", nombres:"GINA ABIGAIL JULCA PAREDES", certificado:"UNIAS1.pdf" },
{ dni: "20250903", nombres:"ANALI KRISTEL ALAYO VILELA", certificado:"UNIAS1.pdf" },
{ dni: "48467084", nombres:"GHILMAR HUAMANTTUPA GÓNGORA",certificado:"COREECO.pdf" },
{ dni: "46070557", nombres:"JUAN MANUEL AQUINO CALCINA",certificado:"COREECO.pdf" },
{ dni: "89634710", nombres:"ROSA ADELI RUBIO TIRADO", certificado:"COREECO.pdf" },
{ dni: "34306273", nombres: "LUIS FERNANDO PÉREZ BECERRA", certificado:"COREECO.pdf" },
{ dni: "83528129", nombres: "NILTON EFRAIN MORENO CARAHUATAY", certificado:"COREECO.pdf" },
{ dni: "40619848", nombres: "JHIMY FERNANDO MIRES GOICOCHEA", certificado:"COREECO.pdf" },
{ dni: "99870494", nombres: "LENNIN PAUL SANGAY ASENCIO", certificado:"COREECO.pdf" },
{ dni: "21675638", nombres: "HENNRY FLORES SANCHEZ", certificado:"COREECO.pdf" },
{ dni: "80058328", nombres: "FRAN LUIS TIRADO BUENO", certificado:"COREECO.pdf" },
{ dni: "95604994", nombres: "DEYVI ALEXIS MONZÓN CHICO", certificado:"COREECO.pdf" },
{ dni: "98845594", nombres: "DEINER OLVER LOPEZ ESTELA", certificado:"COREECO.pdf" },
{ dni: "89523526", nombres: "EVER LUIS GUEVARA RAFAEL", certificado:"COREECO.pdf" },
{ dni: "97503036", nombres: "BERCEYLI VARGAS VILLAVICENCIO", certificado:"COREECO.pdf" },
{ dni: "52095992", nombres: "VANESSA WENDOLI VALLEJOS OLORTEGUI", certificado:"COREECO.pdf" },
{ dni: "44941099", nombres: "JOHANNES GIANCARLO RODRIGUEZ ALTAMIRANO", certificado:"COREECO.pdf" },
{ dni: "45540668", nombres: "ERIK GUITIÉRREZ EUGENIO", certificado:"COREECO.pdf" },
{ dni: "74045044", nombres: "ANNY LISSETH REQUEJO ROMÁN", certificado:"COREECO.pdf" },
{ dni: "34024320", nombres: "HUGO HOLDEN DÍAZ LEÓN", certificado:"COREECO.pdf" },
{ dni: "12368742", nombres: "SUSANA ESTHER ADRIANZEN ADRIANZEN", certificado:"COREECO.pdf" },
{ dni: "49867203", nombres: "JOEL ROMERO MENDOZA", certificado:"COREECO.pdf" },
{ dni: "93713771", nombres: "ARACELI PAJARES HUARIPATA", certificado:"COREECO.pdf" },
{ dni: "93161514", nombres: "CARLOS EMANUEL SILVA ALIAGA", certificado:"COREECO.pdf" },
{ dni: "26992491", nombres: "ELESVITA FERNÁNDEZ REGALADO", certificado:"COREECO.pdf" },
{ dni: "90850314", nombres: "ELFER SILVA ABANTO", certificado:"COREECO.pdf" },
{ dni: "63011307", nombres: "ALIPIO ROSAS TOMAS", certificado:"COREECO.pdf" },
{ dni: "42251494", nombres: "SARA RAQUEL RAVINES CUBAS", certificado:"COREECO.pdf" },
{ dni: "68812570", nombres: "ANA MARÍA VALERA ROMERO", certificado:"COREECO.pdf" },
{ dni: "31376426", nombres: "JEREMÍAS MESTANZA REBAZA", certificado:"COREECO.pdf" },
{ dni: "30190346", nombres: "ELVIA MARISOL PUSCAN CULQUI", certificado:"COREECO.pdf" },
{ dni: "98385705", nombres: "JOSEMANUEL CARUAJULCA VENEROS", certificado:"COREECO.pdf" },
{ dni: "98502271", nombres: "JOSÉ ARNOLD VILCA VILCA", certificado:"COREECO.pdf" },
{ dni: "19960881", nombres: "JOSE CARLOS CHAVEZ CARCAUSTO", certificado:"COREECO.pdf" },
{ dni: "56244278", nombres: "PERCY LIPA PAYE", certificado:"COREECO.pdf" },
{ dni: "19131210", nombres: "WILY CHANEL ROQUE TICONA", certificado:"COREECO.pdf" },
{ dni: "49996920", nombres: "CRISTIAN QUISPE ZAPANA", certificado:"COREECO.pdf" },
{ dni: "85027630", nombres: "JERSY LANDER PARI MAMANI", certificado:"COREECO.pdf" },
{ dni: "86153775", nombres: "GABRIELA ASUNCION ESCOBEDO PACHECO", certificado:"COREECO.pdf" },
{ dni: "78559482", nombres: "LUZ YENNIFER TURPO APAZA", certificado:"COREECO.pdf" },
{ dni: "69463429", nombres: "ABDON JHORDAN SUCASACA SUCASACA", certificado:"COREECO.pdf" },
{ dni: "76331472", nombres: "FLOR MILAGROS FLORES OLARTEGUI", certificado:"COREECO.pdf" },
{ dni: "46400985", nombres: "JACKELINE RUTH ZARAZA MAMANI", certificado:"COREECO.pdf" },
{ dni: "18780549", nombres: "RAUL LENIN CARCAUSTO MAMANI", certificado:"COREECO.pdf" },
{ dni: "18715864", nombres: "SAMIR NIVARDO SONCCO CACERES", certificado:"COREECO.pdf" },
{ dni: "89987162", nombres: "FRANKLIN RAFAEL MAITA", certificado:"COREECO.pdf" },
{ dni: "62842575", nombres: "RONALD TITO MAMANI", certificado:"COREECO.pdf" },
{ dni: "71258077", nombres: "ÑOL EMERSON TAZA APAZA", certificado:"COREECO.pdf" },
{ dni: "37499402", nombres: "WINNY LESLY QUISPE GUTIERREZ", certificado:"COREECO.pdf" },
{ dni: "32863971", nombres: "ABRAHAM ENCINAS QUENTA", certificado:"COREECO.pdf" },
{ dni: "38240045", nombres: "KAREN EVELYN LIVISI JIMENEZ", certificado:"COREECO.pdf" },
{ dni: "83847646", nombres: "YHONY EDY AQUINO CAHUAPAZA", certificado:"COREECO.pdf" },
{ dni: "33200974", nombres: "DIANETH MACHACA LAURA", certificado:"COREECO.pdf" },
{ dni: "82890898", nombres: "HIRLEY YULIÑO QUISPE QUISPE", certificado:"COREECO.pdf" },
{ dni: "12863193", nombres: "JORGE WILLIAM PAREDES CHAMBILLA", certificado:"COREECO.pdf" },
{ dni: "80742509", nombres: "FELIZ RAUL MURILLO QUISPE", certificado:"COREECO.pdf" },
{ dni: "67841207", nombres: "CLIVER MAGNO ALBERTO VENTURA", certificado:"COREECO.pdf" },
{ dni: "13588820", nombres: "JENNY MARIBEL QUISPE CALIZAYA", certificado:"COREECO.pdf" },
{ dni: "13588820", nombres: "JENNY MARIBEL QUISPE CALIZAYA", certificado:"COREECO.pdf" },
{ dni: "28105159", nombres: "DENNIS CLUDE IRPANOCCA PACHECO", certificado:"COREECO.pdf" },
{ dni: "93112956", nombres: "BRENDA BIANCA TORO VALEROS", certificado:"COREECO.pdf" },
{ dni: "70749182", nombres: "YASMIN NAYELI SOTO VILCA", certificado:"COREECO.pdf" },
{ dni: "58675311", nombres: "RONALDO PAUL CALCINA CALCINA", certificado:"COREECO.pdf" },
{ dni: "79480023", nombres: "BRAYAN HILARIO HUANCA CHOQUEHUANCA", certificado:"COREECO.pdf" },
{ dni: "56119584", nombres: "GIANI JAMELI CRUZ VILAVILA", certificado:"COREECO.pdf" },
{ dni: "96629911", nombres: "ANDERSON ROMARIO TICONA CONTRERAS", certificado:"COREECO.pdf" },
{ dni: "21411053", nombres: "KEVIN ALY ENRIQUEZ LLANOS", certificado:"COREECO.pdf" },
{ dni: "93717392", nombres: "YAMEL ANTONY HUANCA CHAMBI", certificado:"COREECO.pdf" },
{ dni: "24383736", nombres: "LUZ ALEJANDRA MAMANI LARICO", certificado:"COREECO.pdf" },
{ dni: "46995080", nombres: "YANIRA LIZBETH FUENTES VARGAS", certificado:"COREECO.pdf" },
{ dni: "47069456", nombres: "YEREMI DEAN HUARACHI LAURA", certificado:"COREECO.pdf" },
{ dni: "27836145", nombres: "JHAN CARLOS MAMANI CARRILLO", certificado:"COREECO.pdf" },
{ dni: "27566359", nombres: "BRAYAN LIZANDRO CONDORI MAMANI", certificado:"COREECO.pdf" },
{ dni: "81329547", nombres: "EDSON YAMIL CALIZAYA PAREDES", certificado:"COREECO.pdf" },
{ dni: "97365623", nombres: "PAOLO ALEJANDRA PAREDES YUCRA", certificado:"COREECO.pdf" },
{ dni: "32503807", nombres: "SHEILA BRIDNEY HUALLPA QUISPE", certificado:"COREECO.pdf" },
{ dni: "22011545", nombres: "YASMIRA SAGUA MAQUERA", certificado:"COREECO.pdf" },
{ dni: "56156221", nombres: "NERY LUZ TITO YANAPA", certificado:"COREECO.pdf" },
{ dni: "28057060", nombres: "LEIDY LISETH ARPITA SUCAPUCA", certificado:"COREECO.pdf" },
{ dni: "67641323", nombres: "BEATRIZ CALCINA MERMA", certificado:"COREECO.pdf" },
{ dni: "97615408", nombres: "MILAGROS COILA AVILA", certificado:"COREECO.pdf" },
{ dni: "82076757", nombres: "MARISOL YUCASI CALAPUJA", certificado:"COREECO.pdf" },
{ dni: "23611908", nombres: "MARCIA SUAÑA QUISPE", certificado:"COREECO.pdf" },
{ dni: "43941931", nombres: "EDISON CRISTIAN VILCA MAMANI", certificado:"COREECO.pdf" },
{ dni: "38709564", nombres: "ANA VANESSA COPA PANCA", certificado:"COREECO.pdf" },
{ dni: "44298942", nombres: "STEVEN VICTOR CHAMBY BRAVO", certificado:"COREECO.pdf" },
{ dni: "72242498", nombres: "JAIR SHANNON PAYE PÉREZ", certificado:"COREECO.pdf" },
{ dni: "38876688", nombres: "JACQUELINE YULISSA LUNA MERMA", certificado:"COREECO.pdf" },
{ dni: "75163271", nombres: "SHEYLA MAGALY CHATA MAMANI", certificado:"COREECO.pdf" },
{ dni: "70644919", nombres: "JOSE MANUEL MAMANI HUARCAYA", certificado:"COREECO.pdf" },
{ dni: "50180029", nombres: "JIMENA ROUS OLIVERA JIMÉNEZ ", certificado:"COREECO.pdf" },
    { dni: "36634121", nombres: "LUZ FERNANDA TARCO NINA", certificado:"COREECO.pdf" },
    { dni: "60756741", nombres: "PIERO XAVIER CERQUERA HERNÁNDEZ", certificado:"COREECO.pdf" },
    { dni: "16756592", nombres: "JHOEL COSME ESTRADA RAMOS", certificado:"COREECO.pdf" },
{ dni: "80403447", nombres: "JULIO CÉSAR CANAHUIRE HUAMANI", certificado:"COREECO.pdf" },
    { dni: "41627193", nombres: "YAJAIRA ANAI ORTIZ TACO", certificado:"COREECO.pdf" },
    { dni: "76699336", nombres: "ALFREDO CALLOAPAZA CCAMA", certificado:"COREECO.pdf" },
    { dni: "18594491", nombres: "NORKA VRISS CURRO CHURA", certificado:"COREECO.pdf" },
{ dni: "18872792", nombres: "YORK JHAFFEP HUAMÁN PONTECIL", certificado:"COREECO.pdf" },
{ dni: "48423596", nombres: "JHON RONALDO PANCCA QUISPE", certificado:"COREECO.pdf" },
{ dni: "16847859", nombres: "ANTHONY JOHAN UHUINA QUISPE", certificado:"COREECO.pdf" },
{ dni: "80610119", nombres: "HANA JUSHIRA DAVILA RUPAILLA", certificado:"COREECO.pdf" },
{ dni: "25294439", nombres: "YOSGALY ROJAS HERMOZA", certificado:"COREECO.pdf" },
{ dni: "35211016", nombres: "ELIENAI GIEZI AUCCAPURE CHALLCO", certificado:"COREECO.pdf" },
{ dni: "75319322", nombres: "YANETH GONZALES ALAMANZA", certificado:"COREECO.pdf" },
{ dni: "65666494", nombres: "CARLOS ALBERTO CALLAÑAUPA JESUS", certificado:"COREECO.pdf" },
{ dni: "68221305", nombres: "BETSY GABRIELA CASTRO CANSAYA", certificado:"COREECO.pdf" },
{ dni: "81742002", nombres: "EDDY RODRIGO ARAGON HUAMANI", certificado:"COREECO.pdf" },
{ dni: "65148442", nombres: "FLOR DE MARIA HUILLCA VARGAS", certificado:"COREECO.pdf" },
{ dni: "39889985", nombres: "LEANDRO FABIAN VALVERDE FARFAN", certificado:"COREECO.pdf" },
{ dni: "34415929", nombres: "OWEN DEISER BAUTISTA HURTADO", certificado:"COREECO.pdf" },
{ dni: "31444482", nombres: "PAMELA YABAR NUÑEZ", certificado:"COREECO.pdf" },
{ dni: "51726152", nombres: "KARLA VANESSA CELI BANCES", certificado:"COREECO.pdf" },
{ dni: "42367683", nombres: "NEICER JOAQUIN FLORES SOSA", certificado:"COREECO.pdf" },
{ dni: "99329931", nombres: "RICKY RONAL QUISPE BENIQUE", certificado:"COREECO.pdf" },
{ dni: "93357554", nombres: "ZULMA DEYVA PARI CCOPA", certificado:"COREECO.pdf" },
{ dni: "64520935", nombres: "FLAVIO QUISPE COAQUIRA", certificado:"COREECO.pdf" },
{ dni: "89883009", nombres: "RONALD CALLATA QUISPE", certificado:"COREECO.pdf" },
{ dni: "45861679", nombres: "ROSSY DORIS MAMANI QUISPE", certificado:"COREECO.pdf" },
{ dni: "36865665", nombres: "DENIS VIKY MAMANI MAMANI", certificado:"COREECO.pdf" },
{ dni: "63633562", nombres: "JESUS ALBERTO MACHACA BELIZARIO", certificado:"COREECO.pdf" },
{ dni: "48134815", nombres: "EDWIN MAMANI CARBAJAL", certificado:"COREECO.pdf" },
{ dni: "27990286", nombres: "MIIGUEL ANGEL HIRPANOCCA MAMANI", certificado:"COREECO.pdf" },
{ dni: "39410332", nombres: "JORGE PASCUAL VALERIANO PARI", certificado:"COREECO.pdf" },
{ dni: "18326707", nombres: "YONEL RUFINO HUAHUASONCCO MAMANI", certificado:"COREECO.pdf" },
{ dni: "36865665", nombres: "DENIS VIKY MAMANI MAMANI", certificado:"COREECO.pdf" },
{ dni: "56770333", nombres: "FIDEL MARCELO CÁCERES LÓPEZ", certificado:"COREECO.pdf" },
{ dni: "43884167", nombres: "ROCÍO LIZBET AYALA VARGAS", certificado:"COREECO.pdf" },
{ dni: "71407346", nombres: "MAYCOL EDYSON YANQUI PINTO", certificado:"COREECO.pdf" },
{ dni: "61282844", nombres: "NIDWAR ATAMARI RODRIGUEZ", certificado:"COREECO.pdf" },
{ dni: "30057454", nombres: "EDWIN GIL QUISPE", certificado:"COREECO.pdf" },
{ dni: "97174422", nombres: "MARY KELMA KEY ADCO PUMA", certificado:"COREECO.pdf" },
{ dni: "65521082", nombres: "YIOMIRA AMANQUI QUIZA", certificado:"COREECO.pdf" },
{ dni: "89695211", nombres: "RUTH KAREN PACCO YANA", certificado:"COREECO.pdf" },
{ dni: "45530068", nombres: "ELISABLETH EDITH YANQUI CANAZA", certificado:"COREECO.pdf" },
{ dni: "35434707", nombres: "EDITH MAMANI CHIPANA", certificado:"COREECO.pdf" },
{ dni: "93883218", nombres: "ROY ALEX LERMA SUCASACA", certificado:"COREECO.pdf" },
{ dni: "43143990", nombres: "VITALIANO ENRIQUEZ MAMAN", certificado:"COREECO.pdf" },
{ dni: "25007415", nombres: "JAMIL ROBERTZON MAMANI HUAYNACHO", certificado:"COREECO.pdf" },
{ dni: "90421498", nombres: "FIORELA ELIZABETH GUEVARA FERNÁNDEZ", certificado:"COREECO.pdf" },
{ dni: "30916930", nombres: "JAIME JULIO CARRIÓN QUISPE", certificado:"COREECO.pdf" },
{ dni: "65638639", nombres: "CLEVER OMAR AGUILAR CARUAJULCA", certificado:"COREECO.pdf" },
{ dni: "90152222", nombres: "FRANK TONY EDWIN ALANOCA CHOQUE", certificado:"COREECO.pdf" },
{ dni: "27321207", nombres: "DACELI ROSARIO ANCHAPURI CRUZ", certificado:"COREECO.pdf" },
{ dni: "53325271", nombres: "JEAMPIER EDWARD AQUINO ALAVE", certificado:"COREECO.pdf" },
{ dni: "97183557", nombres: "MARCIA FERNANDA ARA LAQUE", certificado:"COREECO.pdf" },
{ dni: "67093588", nombres: "MYRIAN KAREN BARRIOS SALLUCA", certificado:"COREECO.pdf" },
{ dni: "37219638", nombres: "CESAR ANDRÉS BEJARANO VILLALTA", certificado:"COREECO.pdf" },
{ dni: "42771155", nombres: "MAURO DANIEL CABRERA ARO", certificado:"COREECO.pdf" },
{ dni: "19998341", nombres: "ESMERALDA LIZ CACERES CCALLO", certificado:"COREECO.pdf" },
{ dni: "50806123", nombres: "BARBARA NICOLE CANCHOS GALINDO", certificado:"COREECO.pdf" },
{ dni: "16233042", nombres: "DINA EDITH CAPAJAÑA QUISPE", certificado:"COREECO.pdf" },
{ dni: "54416529", nombres: "YHOWIS ROMARIO CCALLI CHINO", certificado:"COREECO.pdf" },
{ dni: "48772233", nombres: "JEAN KEVIN CCALLI MAMANI", certificado:"COREECO.pdf" },
{ dni: "91100187", nombres: "KAREN KATHERINE CHACHAQUE CALDERON", certificado:"COREECO.pdf" },
{ dni: "69810567", nombres: "LISETH SINTIA CHALCO LARICO", certificado:"COREECO.pdf" },
{ dni: "47740724", nombres: "EDWIN DANY CHOQUE CALDERON", certificado:"COREECO.pdf" },
{ dni: "38864855", nombres: "MARY MELANY CHOQUEJAHUA CACHICATARI", certificado:"COREECO.pdf" },
{ dni: "87250230", nombres: "LAURA ANDREA CHUCUYA TICONA", certificado:"COREECO.pdf" },
{ dni: "81701800", nombres: "JHONNIOR CRISTIAN COAQUIRA JINEZ", certificado:"COREECO.pdf" },
{ dni: "12229575", nombres: "YESENIA CONDORI INCACUTIPA", certificado:"COREECO.pdf" },
{ dni: "69464698", nombres: "MARY SOLEDAD COPARI ARRATIA", certificado:"COREECO.pdf" },
{ dni: "78328169", nombres: "DANIELA ALLISON GALLEGOS MAMANI", certificado:"COREECO.pdf" },
{ dni: "87500299", nombres: "JIMENA MILAGROS MACHACA CHATA", certificado:"COREECO.pdf" },
{ dni: "56978398", nombres: "MARÍA ALEJANDRA GONZALES TEVES", certificado:"COREECO.pdf" },
{ dni: "68340382", nombres: "JUAN ELIAS HUALLPA AROCUTIPA", certificado:"COREECO.pdf" },
{ dni: "44865312", nombres: "ALVARO JAVIER JAPURA CALISAYA", certificado:"COREECO.pdf" },
{ dni: "64395454", nombres: "JESSICA MAMANI APAZA", certificado:"COREECO.pdf" },
{ dni: "11334508", nombres: "AMERLI WASHINGTON MAMANI CCALLO", certificado:"COREECO.pdf" },
{ dni: "29322191", nombres: "JHOJAN ALEXIS ZELA MAMANI", certificado:"COREECO.pdf" },
{ dni: "33818589", nombres: "GILMA MAMANI QUISPE", certificado:"COREECO.pdf" },
{ dni: "90106668", nombres: "SONYA SMITH MAMANI MACHACA", certificado:"COREECO.pdf" },
{ dni: "60764880", nombres: "ANDREA NATALYA MAMANI CORONEL", certificado:"COREECO.pdf" },
{ dni: "58644986", nombres: "NIEVES ESPERANZA HUALLPA APAZA", certificado:"COREECO.pdf" },
{ dni: "80287088", nombres: "HEIDY BRANDY QUISPE ZAPANA", certificado:"COREECO.pdf" },
{ dni: "62761798", nombres: "KELLY NOHEMI SUCASAIRE APAZA", certificado:"COREECO.pdf" },
{ dni: "76151186", nombres: "DORA NANCY BARRIOS QUISPE", certificado:"COREECO.pdf" },
{ dni: "48534511", nombres: "NORMA PELAEZ RIVERA", certificado:"COREECO.pdf" },
{ dni: "28335426", nombres: "AYDEE ZARAI PARI MAMANI", certificado:"COREECO.pdf" },
{ dni: "53732556", nombres: "MELVYN HUDATH MAMANI PACOMPIA", certificado:"COREECO.pdf" },
{ dni: "41624517", nombres: "LINO MAMANI LIPA", certificado:"COREECO.pdf" },
{ dni: "46915374", nombres: "BRAYAN ANTONY MAYORGA MAMANI", certificado:"COREECO.pdf" },
{ dni: "96558193", nombres: "JOVANISI DANIELA MORENO CAÑI", certificado:"COREECO.pdf" },
{ dni: "98864560", nombres: "ABRAHAM MELITON CONTRERAS VARGAS", certificado:"COREECO.pdf" },
{ dni: "90048689", nombres: "SAYDA STEFANI MACHACA MACHACA", certificado:"COREECO.pdf" },
{ dni: "97649712", nombres: "NEIRA DIAZ JOSÉ GABRIEL", certificado:"COREECO.pdf" },
{ dni: "56644401", nombres: "ESTEBAN FRANCISCO VERA MAMANI", certificado:"COREECO.pdf" },
{ dni: "58439802", nombres: "INDIRA NATALIE APAZA LARICO", certificado:"COREECO.pdf" },
{ dni: "22079223", nombres: "JACKELIN MILAGROS RAMIREZ ALIAGA", certificado:"COREECO.pdf" },
{ dni: "73647838", nombres: "LUÍS GIAMPIERO JACO CARTAGENA", certificado:"COREECO.pdf" },
{ dni: "68212440", nombres: "DANIELLA ARLETTE HURTADO BARRIONUEVO", certificado:"COREECO.pdf" },
{ dni: "63207539", nombres: "RUT NOEMI CHUQUIMAMANI QUISPE", certificado:"COREECO.pdf" },
{ dni: "68885012", nombres: "ALEX WILBER HUACASI QUISPE", certificado:"COREECO.pdf" },
{ dni: "92531895", nombres: "DEYSI KARINA AÑAMURO QUISPE", certificado:"COREECO.pdf" },
{ dni: "47358532", nombres: "STIVE JUNIOR APAZA COARI", certificado:"COREECO.pdf" },
{ dni: "35033709", nombres: "FABRICIO JOSUE PACCO APAZA", certificado:"COREECO.pdf" },
{ dni: "30185936", nombres: "DARIO JOSE PILCO ESTACA", certificado:"COREECO.pdf" },
{ dni: "58788929", nombres: "YANETH QUIÑONEZ COTRADO", certificado:"COREECO.pdf" },
{ dni: "19760029", nombres: "TONY FRANK QUISPE AYCACHI", certificado:"COREECO.pdf" },
{ dni: "98062216", nombres: "LESLY ARACELI ROJAS VÁSQUEZ", certificado:"COREECO.pdf" },
{ dni: "15483757", nombres: "VANESA LEONOR RIVERA TUYO", certificado:"COREECO.pdf" },
{ dni: "53191987", nombres: "RODRIGO DANNY ROSAS PACCI", certificado:"COREECO.pdf" },
{ dni: "64535530", nombres: "TATIANA MARGEORIT TACILLA CASTREJON", certificado:"COREECO.pdf" },
{ dni: "43637271", nombres: "HAYDE ROXANA TICONA TICONA", certificado:"COREECO.pdf" },
{ dni: "64089873", nombres: "ANTHONY QUINN VALERIANO QUISPE", certificado:"COREECO.pdf" },
{ dni: "27527500", nombres: "ESPERANZA XIOMARA SALGADO CHURA", certificado:"COREECO.pdf" },
{ dni: "34955362", nombres: "JESÚS MANUEL SEBASTIÁN MENDÍA TORRE", certificado:"COREECO.pdf" },
{ dni: "41566325", nombres: "CAROL FERNANDA RAMOS VALENZUELA", certificado:"COREECO.pdf" },
{ dni: "27118476", nombres: "DORA AMELIA PACO TORRES", certificado:"COREECO.pdf" },
{ dni: "19985657", nombres: "ALEXANDER RONALDO SERRANO VILCA", certificado:"COREECO.pdf" },
{ dni: "80622086", nombres: "ELIZABETH MILAGROS MAMANI MAMANI", certificado:"COREECO.pdf" },
{ dni: "68589400", nombres: "NOELY CAÑAZACA QQUENTA", certificado:"COREECO.pdf" },
{ dni: "93147987", nombres: "CESAR ANTONIO BRICEÑO ROMERO", certificado:"COREECO.pdf" },
{ dni: "91602740", nombres: "ALESSANDRA MARGARETH SUCASACA ROBLES", certificado:"COREECO.pdf" },
{ dni: "29605513", nombres: "WILMER ISPILCO LOPEZ", certificado:"COREECO.pdf" },
{ dni: "27679337", nombres: "MARÍA DEL CIELO GUEVARA QUIROZ", certificado:"COREECO.pdf" },
{ dni: "16178722", nombres: "JHOAN MANUEL BAUTISTA YGNACIO", certificado:"COREECO.pdf" },
{ dni: "12059122", nombres: "CRISTHIAN EDGAR ACUÑA VILCHEZ", certificado:"COREECO.pdf" },
{ dni: "17881490", nombres: "JONATAN OBED CARRASCO VÁSQUEZ", certificado:"COREECO.pdf" },
{ dni: "29647500", nombres: "YESSICA YAMIRA JULCAMORO LLANOS", certificado:"COREECO.pdf" },
{ dni: "43810371", nombres: "YANNELA NICOL ROJAS VARGAS", certificado:"COREECO.pdf" },
{ dni: "17666214", nombres: "LUZ ANGELICA CARMONA ALCANTARA", certificado:"COREECO.pdf" },
{ dni: "15687494", nombres: "YANELA LIZETH BARBOZA BUSTAMANTE", certificado:"COREECO.pdf" },
{ dni: "50472218", nombres: "EDUARDO ENRIQUE TASILLA DURAND", certificado:"COREECO.pdf" },
{ dni: "36341293", nombres: "NILTON EFRAIN MORENO CARAHUATAY", certificado:"COREECO.pdf" },
{ dni: "23748916", nombres: "MAIKEL IMANOL FRIAS MOZOMBITE", certificado:"COREECO.pdf" },
{ dni: "54961256", nombres: "LORENITA MELE URIARTE GUEVARA", certificado:"COREECO.pdf" },
{ dni: "28678550", nombres: "JHON ROBERT HERNANDEZ GUERRERO", certificado:"COREECO.pdf" },
{ dni: "21601828", nombres: "ESTRELLA ROMINA ALVAREZ CABELLOS", certificado:"COREECO.pdf" },
{ dni: "60828168", nombres: "DENIS ABELARDO, VÁSQUEZ TERRONES", certificado:"COREECO.pdf" },
{ dni: "26774749", nombres: "LUIS GUEVARA PÉREZ", certificado:"COREECO.pdf" },
{ dni: "24264003", nombres: "EINER MOISÉS GASTOLOMENDO CUEVA", certificado:"COREECO.pdf" },
{ dni: "52429241", nombres: "DEYBIS URIBE TOCAS CHOROCO", certificado:"COREECO.pdf" },
{ dni: "51773257", nombres: "CESAR ELVIS TERRONES MAMANI", certificado:"COREECO.pdf" },
{ dni: "31578918", nombres: "HÉCTOR GABRIEL MACALOPÚ MEDINA", certificado:"COREECO.pdf" },
{ dni: "21376297", nombres: "EDIVER ROMARIO DÍAZ LEYVA", certificado:"COREECO.pdf" },
{ dni: "21108949", nombres: "DIANA ESTEFANY BARBOZA SANCHEZ", certificado:"COREECO.pdf" },
{ dni: "18478259", nombres: "MARIBEL CUEVA IPARRAGUIRRE", certificado:"COREECO.pdf" },
{ dni: "16152410", nombres: "JAMES JHAIR BARBOZA MONDRAGON", certificado:"COREECO.pdf" },
{ dni: "44971344", nombres: "DARNER HUBERT SÁNCHEZ DÍAZ", certificado:"COREECO.pdf" },
{ dni: "32201132", nombres: "YESICA ISABEL MICHA GOICOCHEA", certificado:"COREECO.pdf" },
{ dni: "15653610", nombres: "WILLIAM RAFAEL ARAUJO MARIN", certificado:"COREECO.pdf" },
{ dni: "36606554", nombres: "MARIANELA NÚÑEZ VÁSQUEZ", certificado:"COREECO.pdf" },
{ dni: "17188453", nombres: "MARK CRHISTOPHER CALUA LÓPEZ", certificado:"COREECO.pdf" },
{ dni: "56654660", nombres: "FABRICIO JOSÉ VÁSQUEZ TERÁN", certificado:"COREECO.pdf" },
{ dni: "29843205", nombres: "CESAR ADRIÁN LEÓN ALVA", certificado:"COREECO.pdf" },
{ dni: "38541232", nombres: "DIEGO MAR OSORIO TELLO", certificado:"COREECO.pdf" },
{ dni: "25736532", nombres: "FIORELA JHANAIRA GUEVARA MENDOZA", certificado:"COREECO.pdf" },
{ dni: "18060467", nombres: "JHOANN ORLANDO CHAVEZ VERA", certificado:"COREECO.pdf" },
{ dni: "42432864", nombres: "ALEXA FABIANA QUIROZ CORTEZ", certificado:"COREECO.pdf" },
{ dni: "41465038", nombres: "DAYANNA MADELEINE PERE DIAZ", certificado:"COREECO.pdf" },
{ dni: "48695918", nombres: "YEFERSON LUIS SILVA MATARA", certificado:"COREECO.pdf" },
{ dni: "62505548", nombres: "ALEXIS LEONED VILLA VÁSQUEZ", certificado:"COREECO.pdf" },
{ dni: "27824803", nombres: "JAANS BRAHIAN LANDEO HERRERAS", certificado:"COREECO.pdf" },
{ dni: "71952231", nombres: "JHEYSON CHOQUE SALON", certificado:"COREECO.pdf" },
{ dni: "46614121", nombres: "SMITH ANDERSON QUISPE MOLINA", certificado:"COREECO.pdf" },
{ dni: "24778291", nombres: "NATALI SALOME GONZALES HUACCHA", certificado:"COREECO.pdf" },
{ dni: "32257368", nombres: "DANNY LEO OBLITAS ARPITA", certificado:"COREECO.pdf" },
{ dni: "56328080", nombres: "DEYSI MENELI VARGAS RODRÍGUEZ", certificado:"COREECO.pdf" },
{ dni: "55657424", nombres: "MADELEY KAREN LANDA VARGAS", certificado:"COREECO.pdf" },
{ dni: "57115133", nombres: "ALBERT SNAIDER HUAMANI SACA", certificado:"COREECO.pdf" },
{ dni: "45049509", nombres: "ROMEO AUDAX QUISPE PACCO", certificado:"COREECO.pdf" },
{ dni: "13185222", nombres: "FIORELLA ISABEL ALVITRES QUISPE", certificado:"COREECO.pdf" },
{ dni: "62294875", nombres: "JEANPIERE VÁSQUEZ VILLANUEVA", certificado:"COREECO.pdf" },
{ dni: "44916664", nombres: "NEY ELAR MENDIA APARICIO", certificado:"COREECO.pdf" },
{ dni: "32171113", nombres: "EMERSON JAIR MARIN PEREZ", certificado:"COREECO.pdf" },
{ dni: "82176795", nombres: "STEVEN ALEJANDRO PAPEL TABOADA", certificado:"COREECO.pdf" },
{ dni: "31383066", nombres: "DIEGO ANDERSON LUDEÑA MEGO", certificado:"COREECO.pdf" },
{ dni: "58257463", nombres: "BRANDON FRANSHESCO ROMERO ELORRIETA", certificado:"COREECO.pdf" },
{ dni: "30542822", nombres: "DIEGO ARMANDO LUCANO CHUNQUE", certificado:"COREECO.pdf" },
{ dni: "98549720", nombres: "RUBHIÑHO FRANCHESCO LAUREL SEQUEIROS", certificado:"COREECO.pdf" },
{ dni: "29578648", nombres: "ZAIRA JESUS HERRERA DIAZ", certificado:"COREECO.pdf" },
{ dni: "76643940", nombres: "JESUS MATEO GIBAJA GUERRA", certificado:"COREECO.pdf" },
{ dni: "82372857", nombres: "EXMARSADAN MUÑOZ ACERO", certificado:"COREECO.pdf" },
{ dni: "48467084", nombres: "ANNY LISSETH REQUEJO ROMÁN", certificado:"COREECO.pdf" },
{ dni: "67381940", nombres: "SANDRO HUAMÁN VÁZQUEZ", certificado:"COREECO.pdf" },
{ dni: "79346098", nombres: "HUBILSER DESLIN MUÑOZ TINOCO", certificado:"COREECO.pdf" },
{ dni: "11769324", nombres: "DIEGO FABRICIO ABANTO GUILLÉN", certificado:"COREECO.pdf" },
{ dni: "20934905", nombres: "ESTHER CULQUI DIAZ", certificado:"COREECO.pdf" },
{ dni: "76669035", nombres: "CARLOS MANUEL GONZALES BERROCAL", certificado:"COREECO.pdf" },
{ dni: "82306113", nombres: "JHONATAN CABRERA SUAREZ", certificado:"COREECO.pdf" },
{ dni: "35787116", nombres: "KEND STEVEN HUAYAN JUÁREZ", certificado:"COREECO.pdf" },
{ dni: "69091669", nombres: "ROBERT SAMUEL CÓRDOVA AYAC", certificado:"COREECO.pdf" },
{ dni: "87990770", nombres: "YONATHAN SUAREZ MALCA", certificado:"COREECO.pdf" },
{ dni: "80766607", nombres: "LISSET GIANINA RAICO CHILÓN", certificado:"COREECO.pdf" },
{ dni: "77450526", nombres: "MARITA DANIELA RAMIREZ AGURTO", certificado:"COREECO.pdf" },
{ dni: "71804979", nombres: "EVER LUIS GUEVARA RAFAEL", certificado:"COREECO.pdf" },
{ dni: "88441145", nombres: "CYNTIA YENIFER TERRONES MARÍN", certificado:"COREECO.pdf" },
{ dni: "80124460", nombres: "JHONATAN OMAR QUINTANA BENAVIDES", certificado:"COREECO.pdf" },
{ dni: "90259017", nombres: "JUAN ABRAHAM ZELADA HUAMAN", certificado:"COREECO.pdf" },
{ dni: "78115318", nombres: "JIMMY KEDWIN MENDOZA APOLITANO", certificado:"COREECO.pdf" },
    { dni: "86909957", nombres: "SONIA LISBETI ACUÑA SILVA", certificado:"COREECO.pdf" },
    { dni: "88077624", nombres: "OSCAR TERRONES LLANOS", certificado:"COREECO.pdf" },
    { dni: "71836774", nombres: "ROBERT HANS HERNÁNDEZ SÁNCHEZ", certificado:"COREECO.pdf" },
    { dni: "62962409", nombres: "STREYSSI ISSAMAR ARANA BRAVO", certificado:"COREECO.pdf" },
    { dni: "88730879", nombres: "JENNIFER SARA CCONISLLA SALCEDO", certificado:"COREECO.pdf" },
    { dni: "80411588", nombres: "GEINER PINEDO QUISPE CARRION", certificado:"COREECO.pdf" },
    { dni: "33631908", nombres: "GINO JAIRO GAITAN MARCELO", certificado:"COREECO.pdf" },
    { dni: "71296468", nombres: "NESTOR RAUL GARAY CASTAÑEDA", certificado:"COREECO.pdf" },
    { dni: "21601828", nombres: "ESTRELLA ROMINA ALVAREZ CABELLOS", certificado:"COREECO.pdf" },
    { dni: "43547467", nombres: "ROBERT YONSEL HUAMAN RAMIREZ", certificado:"COREECO.pdf" },
    { dni: "76446007", nombres: "ERICK HERNÁN LOZANO CHÁVEZ", certificado:"COREECO.pdf" },
    { dni: "68145490", nombres: "JHULSY GUADALUPE CASTRO COTRINA", certificado:"COREECO.pdf" },
    { dni: "86360048", nombres: "NICOLL ANAÍS SILVA JUÁREZ", certificado:"COREECO.pdf" },
    { dni: "31781544", nombres: "MARGIORY BELEN HUAMAN CHAVEZ", certificado:"COREECO.pdf" },
    { dni: "69732861", nombres: "FRANK JEFERSON GUEVARA SANTILLAN", certificado:"COREECO.pdf" },
    { dni: "84295290", nombres: "MARIBELLA SALECSI ROMERO HURTADO", certificado:"COREECO.pdf" },
    { dni: "76305427", nombres: "MIRIAN LOPEZ ESTELA", certificado:"COREECO.pdf" },
    { dni: "12392114", nombres: "JUAN JOSÉ SÁNCHEZ CHICO", certificado:"COREECO.pdf" },
    { dni: "93077033", nombres: "DEYVIS MAYER SILVA DIAZ", certificado:"COREECO.pdf" },
    { dni: "91155010", nombres: "MAYKOL JHEAN LUIS CABRERA RIMARACHIN", certificado:"COREECO.pdf" },
    { dni: "91517820", nombres: "MAX RODRIGO SÁNCHEZ MENDOZA", certificado:"COREECO.pdf" },
    { dni: "83010026", nombres: "GUILLERMO ENRIQUE RAMIREZ LLAQUE", certificado:"COREECO.pdf" },
    { dni: "62889659", nombres: "YERSON ANTONY ABANTO RODRÍGUEZ", certificado:"COREECO.pdf" },
    { dni: "64784287", nombres: "PERCY FABIAN CASTILLO MANAYALLE", certificado:"COREECO.pdf" },
    { dni: "43783565", nombres: "JHERSON ALAÍN RODRÍGUEZ HUAMÁN", certificado:"COREECO.pdf" },
    { dni: "21108949", nombres: "DIANA ESTEFANY BARBOZA SANCHEZ", certificado:"COREECO.pdf" },
    { dni: "93377007", nombres: "LUIS FELIPE IDRUGO QUIROZ", certificado:"COREECO.pdf" },
    { dni: "85888705", nombres: "JHAN ALEX RUIZ BENAVIDES", certificado:"COREECO.pdf" },
    { dni: "68516511", nombres: "JUAN CARLOS COJAL GAMBOA", certificado:"COREECO.pdf" },
    { dni: "90286852", nombres: "ALEX ROBERT CLAVO DÍAZ", certificado:"COREECO.pdf" },
    { dni: "66309498", nombres: "LUCIANA DEL ROSARIO VERÁSTEGUI CAÑARI", certificado:"COREECO.pdf" },
    { dni: "49452440", nombres: "JOHAO ALESSANDRO VIZCARRA AVILA", certificado:"COREECO.pdf" },
    { dni: "94561466", nombres: "KELLY ROXANA COAQUIRA MAMANI", certificado:"COREECO.pdf" },
    { dni: "60471262", nombres: "SARAI LISBETH CÓRDOVA LLANQUE", certificado:"COREECO.pdf" },
    { dni: "45869746", nombres: "DUANER GONZALO BECERRA FIGUEROA", certificado:"COREECO.pdf" },
    { dni: "82032642", nombres: "FABIOLA FERNANDA PARI PEREZ", certificado:"COREECO.pdf" },
    { dni: "44076842", nombres: "ELIZABETH DEL ROSARIO QUISPE MENDOZA", certificado:"COREECO.pdf" },
    { dni: "43611718", nombres: "CLEVER BORIS CHAGUA GUTIERREZ", certificado:"COREECO.pdf" },
    { dni: "88542786", nombres: "LELIS YESSENIA MOLINERO BAUTISTA", certificado:"COREECO.pdf" },
    { dni: "23561747", nombres: "KAREN HUMPIRI CONDORI", certificado:"COREECO.pdf" },
    { dni: "66148739", nombres: "RONNY VERGARA CONDORI", certificado:"COREECO.pdf" },
    { dni: "23015185", nombres: "DIEGO ESTEFANO DEL SOLAR MUÑIZ", certificado:"COREECO.pdf" },
    { dni: "68000789", nombres: "ROCIO HUAYCOCHEA ESQUIVEL", certificado:"COREECO.pdf" },
    { dni: "67859500", nombres: "KATHERINE ALEXANDRA ROJAS SAAVEDRA", certificado:"COREECO.pdf" },
    { dni: "63278696", nombres: "YOJHANA MISCHEL AGUILAR FLORES", certificado:"COREECO.pdf" },
    { dni: "93833591", nombres: "AMILCAR MEDINA FLORES", certificado:"COREECO.pdf" },
    { dni: "43976780", nombres: "ROSA PAMELA ORRILLO QUILICHE", certificado:"COREECO.pdf" },
    { dni: "76297583", nombres: "KARLA VARGAS HERRERA", certificado:"COREECO.pdf" },
    { dni: "22762679", nombres: "MIRIAN ELENA YOPLA PAISIG", certificado:"COREECO.pdf" },
    { dni: "19611170", nombres: "WILSON EDUARDO VARGAS CUBAS", certificado:"COREECO.pdf" },
    { dni: "61048177", nombres: "JOSEPH ALEXANDER CUEVA PAJARES", certificado:"COREECO.pdf" },
    { dni: "70495770", nombres: "MASIEL GERALDINE GAMBOA JIMÉNEZ", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71820264", nombres: "CASTILLO CUZCO MARGARITA DEL CARMEN", certificado:"CECAJ04.pdf" },
    { dni: "73498842", nombres: "POTOSÍ QUISPE JOSÉ GUSTAVO", certificado:"CECAJ04.pdf" },
    { dni: "72434306", nombres: "ALDER GUZMAN LUCANO ORTIZ", certificado:"CECAJ04.pdf" },
    { dni: "17824415", nombres: "JANETH ESTHER NACARINO DÍAZ", certificado:"CECAJ04.pdf" },
    { dni: "41910225", nombres: "CINTIA LORENA PASTOR LEÓN", certificado:"CECAJ04.pdf" },
    { dni: "73469351", nombres: "HUAMAN BECERRA JASMIN IBETH", certificado:"CECAJ04.pdf" },
    { dni: "26717980", nombres: "CASTAÑEDA SILVA OSWALDO", certificado:"CECAJ04.pdf" },
    { dni: "70248637", nombres: "JORGE LUIS ARIAS SALAS", certificado:"CECAJ04.pdf" },
    { dni: "26616758", nombres: "VASQUEZ PERALTA VICTOR ENRIQUE", certificado:"CECAJ04.pdf" },
    { dni: "41914885", nombres: "PAOLO JOEL ANDRÉS ALZAMORA", certificado:"CECAJ04.pdf" },
    { dni: "45361776", nombres: "SANCHEZ ROJAS JHON", certificado:"CECAJ04.pdf" },
    { dni: "71225805", nombres: "MORILLAS NACARINO ANDY", certificado:"CECAJ04.pdf" },
    { dni: "75846576", nombres: "CUEVA PAISIG LUIS ALBERTO", certificado:"CECAJ04.pdf" },
    { dni: "26618054", nombres: "CARLOS OBLITAS PLASENCIA", certificado:"CECAJ04.pdf" },
    { dni: "10219708", nombres: "QUISPE MOGOLLÓN ALICIA", certificado:"CECAJ04.pdf" },
    { dni: "46760379", nombres: "PÉREZ CUSQUISIBÁN MERLY MARDELY", certificado:"CECAJ04.pdf" },
    { dni: "41527967", nombres: "VASQUEZ REGALADO GILMER EDINSON", certificado:"CECAJ04.pdf" },
    { dni: "41142252", nombres: "PAUL ORLANDO RIVERA MUGUERZA", certificado:"CECAJ04.pdf" },
    { dni: "71622703", nombres: "WALTER FACHINI PAREDES CUBAS", certificado:"CECAJ04.pdf" },
    { dni: "47208251", nombres: "MUÑOZ SÁNCHEZ LUZ ELENA", certificado:"CECAJ04.pdf" },
    { dni: "70252003", nombres: "COTRINA BARDALES KARLA ALEJANDRA", certificado:"CECAJ04.pdf" },
    { dni: "26730913", nombres: "ESCOBAR BAZÁN IBE DEL PILAR", certificado:"CECAJ04.pdf" },
    { dni: "44040661", nombres: "GUISSELA MARISOL HERNÁNDEZ GUERRERO", certificado:"CECAJ04.pdf" },
    { dni: "77232958", nombres: "PEREZ CUSQUISIBAN OMAR", certificado:"CECAJ04.pdf" },
    { dni: "72763454", nombres: "CARLOS HARRINSON VÁSQUEZ ORTEGA", certificado:"CECAJ04.pdf" },
    { dni: "44924373", nombres: "ROSARIO CIEZA RUIZ", certificado:"CECAJ04.pdf" },
    { dni: "70675812", nombres: "LUCANO CAMPOS RODRIGO", certificado:"CECAJ04.pdf" },
    { dni: "43731244", nombres: "PEREYRA CHÁVEZ SABINA ESTHER", certificado:"CECAJ04.pdf" },
    { dni: "44305491", nombres: "MANAY MANAY GERALD MIGUEL", certificado:"CECAJ04.pdf" },
    { dni: "04428272", nombres: "ARTURO COLLANTES HOYOS", certificado:"CECAJ04.pdf" },
    { dni: "72516857", nombres: "HUAMAN CHAVEZ MARGIORY BELEN", certificado:"CECAJ04.pdf" },
    { dni: "60964995", nombres: "ESTELA GONZALES ESTEPHANIE RACHEL", certificado:"CECAJ04.pdf" },
    { dni: "47393877", nombres: "CHICLAYO VÁSQUEZ ANA GABRIELA", certificado:"CECAJ04.pdf" },
    { dni: "42130674", nombres: "ROSILLO LLACSAHUANGA JOSÉ MIKEL", certificado:"CECAJ04.pdf" },
    { dni: "41892191", nombres: "IRIS NOHEMY COBA ROJAS", certificado:"CECAJ04.pdf" },
    { dni: "26719869", nombres: "LARA ASCORBE DAVID", certificado:"CECAJ04.pdf" },
    { dni: "72814134", nombres: "VALDIVIA LIMAY ESTHER", certificado:"CECAJ04.pdf" },
    { dni: "26728578", nombres: "ALVA LEÓN ENA MAHELÍ", certificado:"CECAJ04.pdf" },
    { dni: "40503389", nombres: "RUIZ RAMOS VERÓNICA", certificado:"CECAJ04.pdf" },
    { dni: "43667796", nombres: "ARTURO ADOLFO BAZÁN", certificado:"CECAJ04.pdf" },
    { dni: "61444378", nombres: "SÁNCHEZ VILLANUEVA HENRY DAVID", certificado:"CECAJ04.pdf" },
    { dni: "40341769", nombres: "GIL BAZÁN DIANA", certificado:"CECAJ04.pdf" },
    { dni: "26732563", nombres: "VILLANUEVA CORREA ALEX ENRIQUE", certificado:"CECAJ04.pdf" },
    { dni: "15589136", nombres: "LIZARDO LA ROSA PAREDES", certificado:"CECAJ04.pdf" },
    { dni: "42708706", nombres: "SILVA ARCE ROSA MARÍA", certificado:"CECAJ04.pdf" },
    { dni: "26621815", nombres: "EBER MARÍN BOLAÑOS", certificado:"CECAJ04.pdf" },
    { dni: "71228184", nombres: "ALIAGA GALLARDO DIANA ELVIRA", certificado:"CECAJ04.pdf" },
    { dni: "26629091", nombres: "SALAZAR CHÁVEZ RUBEN", certificado:"CECAJ04.pdf" },
    { dni: "71790194", nombres: "MIRANDA SALAZAR RONA", certificado:"CECAJ04.pdf" },
    { dni: "46459526", nombres: "CHACON IZQUIERDO MOISES", certificado:"CECAJ04.pdf" },
    { dni: "71077265", nombres: "SÁNCHEZ DÍAZ ANGIE MICHELLE", certificado:"CECAJ04.pdf" },
    { dni: "73338193", nombres: "PEDRO JOSUÉ CASAS CAPUÑAY", certificado:"CECAJ04.pdf" },
    { dni: "73469351", nombres: "HUAMAN BECERRA JASMIN IBETH", certificado:"CECAJ04.pdf" },
    { dni: "71456052", nombres: "JAIME JULIO CARRION QUISPE", certificado:"CECAJ04.pdf" },
    { dni: "26600947", nombres: "GARAY MONTAÑEZ HÉCTOR EMILIO", certificado:"CECAJ04.pdf" },
    { dni: "71456062", nombres: "CARRIÓN QUISPE JAIME JULIO", certificado:"CECAJ04.pdf" },
    { dni: "70659076", nombres: "ANA LESLY ROJAS CHACÓN", certificado:"CECAJ04.pdf" },
    { dni: "00001105", nombres: "LUZ KARINA MONZÓN JARA", certificado:"CECAJ04.pdf" },
    { dni: "00001104", nombres: "MASIEL GERALDINE GAMBOA JIMÉNEZ", certificado:"CECAJ04.pdf" },
    { dni: "72737499", nombres: "VASQUEZ VASQUEZ, MARIA ANTHONELLA", certificado:"CECAJ04.pdf" },
    { dni: "00002025", nombres: " ", certificado:"CERTIFICADO TRAINING.pdf" },
    { dni: "74991135", nombres: "JEFERSON RODRIGO CORONADO SOTO", certificado:"CURSO IA.pdf" },
    { dni: "26956394", nombres: "AGUSTINA SOLANO PAREDES", certificado:"CURSO IA.pdf" },
    { dni: "70575275", nombres: "CORDOVA MUÑOZ ANGELLA MILAGRITOS", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "00122024", nombres: "BUENO MEDINA JOSE LUIS", certificado:"CERTIFICADO CONVENCIÓN PONENTE.pdf" },
    { dni: "71080639", nombres: "PALACIOS VALDERRAMA EDINSON JONATHAN", certificado:"CERTIFICADO CONVENCIÓN PONENTE.pdf" },
    { dni: "08297889", nombres: "FERNANDO ORTIZ AGUILAR", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "45913670", nombres: "ING. HUGO WALTER MEDINA BUENO", certificado:"METODOLOGIAS DE ENSEÑANZA.pdf" },
    { dni: "74532498", nombres: "EDICSON JHOEL SILVA CHIROQUE", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "45289899", nombres: "ALBERT DAVID CALDERON LAMA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "42661736", nombres: "YULIANA ELOISA RAMIREZ AÑAZCO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "00001234", nombres: "LICELY YONALY MANOSALVA CAMPOS", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "70072909", nombres: "JUAN MANUEL ESPINOZA VALDIVIEZO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "60943094", nombres: "GERALDINE BEATRIZ BARRETO VARGAS", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72772441", nombres: "Jhenny Lisbeth Vásquez Huamán", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71374842", nombres: "Analí del Carmen Culqui Cachay", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "70248637", nombres: "JORGE LUIS ARIAS SALAS", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "73937497", nombres: "GREYS LILETH AMBROSIO YUPANQUI", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "74475694", nombres: "GUEVARA COBA, DILMER", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72687666", nombres: "ENMANUEL ANTONY LUCANO CHUNQUE", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "74961266", nombres: "ANGEL ESPINOZA GUERRA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "75148667", nombres: "VÍCTOR ALEXANDER CHUQUILIN GAMBOA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "41726292", nombres: "GONZALO MESTANZA SAMAN", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "75364260", nombres: "CHÁVEZ CHÁVEZ JORDAN NOLBERTO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72287785", nombres: "CHRISTOPHER AARÓN MALCA TAFUR", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "76808518", nombres: "ERIKA MARICIELO CHUQUILIN HERRERA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "76789756", nombres: "ERIKA LISSET LLICO CHUNQUE", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "74558426", nombres: "EMERSON FUSTAMANTE SÁNCHEZ", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "73270571", nombres: "YOLIZBETH NOEMÍ CERQUIN ORRILLO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "73415924", nombres: "JHAMPIERE JHERENMY HUAMAN TORRES", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "73270571", nombres: "YOLIZBETH NOEMÍ CERQUIN ORRILLO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "77019091", nombres: "JHON KEVIN VÁSQUEZ ROJAS", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "75900456", nombres: "ANAPAULA DÍAZ MONTOYA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "73535301", nombres: "VICTOR HUGO VILLEGAS DÍAZ", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71855065", nombres: "ERICK JHORDAN TORRES QUISPE", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "77077082", nombres: "ARIAS CULQUE STEPHANIE NAYELY", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "74949730", nombres: "DENNIS ADRIAN MURGA CHILON", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "76879214", nombres: "LILIANA RODRÍGUEZ FERNÁNDEZ", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "70611922", nombres: "CHRISTIAN JOEL VALENCIA TACILLA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71228184", nombres: "DIANA ELVIRA ALIAGA GALLARDO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71105344", nombres: "MAYRA YAMILE GÁLVEZ VERASTEGUI", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72437904", nombres: "VIVIANA ISABEL MACHUCA GOICOCHEA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72536460", nombres: "JHAN BREYNER MARÍN TAPIA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71345597", nombres: "LUZ KARINA MONZÓN JARA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "77035052", nombres: "GUEVARA DELGADO GUILMER JOSUE", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "75088745", nombres: "YHENY YASMÍN RODRÍGUEZ CABELLOS", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71241314", nombres: "ELVIS HUACCHA RAICO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72388433", nombres: "ANDERSON JAIR PULACHE ATO", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "75513663", nombres: "BRISA MARIANELA SILVA ZAPATA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "71870614", nombres: "MARYURI VERONIKA CORNEJO CALDERON", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "75121290", nombres: "MARITZA DEL PILAR GARCÍA IPANAQUÉ", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "72753758", nombres: "JIMÉNEZ FLORES ELKIA", certificado:"CERTIFICADO CONVENCIÓN 2024.pdf" },
    { dni: "41714324", nombres: "Rivera Cardozo Pedro Lito", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "45262156", nombres: "ERIK ADRIAN MONTOYA TERRONES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "04824192", nombres: "ROLANDO ALBERTO MOLINA BOCANGEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "46041552", nombres: "INCIO VARGAS MILAGROS DEL SOCORRO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08297889", nombres: "Fernando Ortiz Aguilar", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09817348", nombres: "JOSÉ ADOLFO HINOJOSA PÉREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09817348", nombres: "Rullierd Sotomayor Terrones", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09817348", nombres: "JOHANSON SÁNCHEZ OMAR ALONSO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72371599", nombres: "MONZÓN CHICO DEYVI ALEXIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09312696", nombres: "César Roberto Mendoza Valencia", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70181748", nombres: "MICHA CHUQUIVIGUEL JHOANA GABRIELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73670203", nombres: "BURGA RIVERA KATHERINE MARICIELO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75364260", nombres: "CHÁVEZ CHÁVEZ JORDAN NOLBERTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "40822252", nombres: "Wilbert Estrada Cuno", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "23857609", nombres: "JAIME MAXI CALLE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21415818", nombres: "JORGE LUIS FERNANDO RIVERA FIGUEROA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77035052", nombres: "GUEVARA DELGADO GUILMER JOSUE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21413192", nombres: "NANCY EMILIA SANTANDER FLORES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "40014331", nombres: "HUMBERTO AGUSTÍN REYES CAMPOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70181352", nombres: "EMI SOFIA ROBLEDO CHAVEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72690098", nombres: "BUSTAMANTE CARRANZA ALEX ANTHONY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "43520326", nombres: "CLAUDIA ROSSANA POMA GARCÍA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73434947", nombres: "YANET BAUTISTA ROQUE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09073969", nombres: "Francisco Fernando Morante Jines", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09438230", nombres: "SUSANA GEOGINA CÁCEDA ANGLAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "31033024", nombres: "STEFFEN AGUIRRE HELGA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "19952034", nombres: "PAREDES BALVIN FIDEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "42207417", nombres: "DÁVILA TARRILLO EDGAR ALEXANDER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72621050", nombres: "Gianpear Peter Santisteban Tavara", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41100313", nombres: "CORREA SÁNCHEZ ELVIA MILAGROS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41196830", nombres: "MURRUGARRA MEDINA KATIA EVELINA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09173009", nombres: "Nimia Elvi Calixto Espinoza", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08197476", nombres: "Henry William Izquierdo Larrea", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "46354322", nombres: "LOZANO PUENTE DE LA VEGA BRUCE MANUEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "40078181", nombres: "FERNÁNDEZ DÍAZ MERY CLAUDINA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72466850", nombres: "Rullierd Guilmar Sotomayor Terrones", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "17881271", nombres: "CASTILLO RADAS WALTER EDUARDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72441262", nombres: "HUAMAN GUAYAC DELIA YAQUELI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60959501", nombres: "CRUZADO BECERRA SHEYLA MARIELENA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72441262", nombres: "HUAMAN GUAYAC DELIA YAQUELI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60959501", nombres: "CRUZADO BECERRA SHEYLA MARIELENA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09548940", nombres: "JOSÉ ANTONIO CHUMACERO CALLE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72160425", nombres: "MARIA SOFIA VILCARROMERO SANDOVAL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73495597", nombres: "MERY MOSQUEDA ALBERCA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "29270275", nombres: "CESAR AUGUSTO BRAVO FEBRES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21409489", nombres: "PARIONA MARQUEZ JOSE LUIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21575810", nombres: "MENDOZA REJAS JANET NATALIA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "05405399", nombres: "PINEDO MARIN CYNTHIA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "26687456", nombres: "CUSTODIO BENZUNCE HENRY AMADEO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70248637", nombres: "ARIAS SALAS JORGE LUIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73535301", nombres: "VILLEGAS DÍAZ VICTOR HUGO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74138505", nombres: "Alvitres Quispe Fiorella Isabel", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "28308818", nombres: "Munaylla Guerra Virginia Delma", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "15373023", nombres: "Rolando Gustavo Garcia Calderón", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75582487", nombres: "ALVAREZ ROBLEDO ANTHONNY HUMBERTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60994696", nombres: "CAMPOS AVALOS YONATHAN LEONED", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72784992", nombres: "CUBAS SOLSOL JHARRYSON JHAIR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70575705", nombres: "HUAMAN PILCO PEDRO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76388637", nombres: "MANCHAY AYAY JIMENA MABEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73532346", nombres: "MEJIA QUIROZ ANDY JAVIER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74431552", nombres: "TORRES VELA MAGALITH MERCEDES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73388355", nombres: "PÉREZ VASQUEZ TATIANA JHONMITH", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73695236", nombres: "PUERTA CULQUI JHOSELIN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76002831", nombres: "SANCHEZ VASQUEZ LUZ ELIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72784956", nombres: "SERVAN SANTILLAN ELIDA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75900036", nombres: "VILLALOBOS ROJAS MIRELIA ARELY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75618063", nombres: "SILVA CHAVEZ BRYAN ALEX", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73480952", nombres: "HUAMAN ILIQUIN RENSON JHANPIER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71995539", nombres: "JOHANSON SÁNCHEZ OMAR ALONSO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73480952", nombres: "HUAMAN ILIQUIN RENSON JHANPIER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60338803", nombres: "DELGADO GARCÍA ANTONY GABRIEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74616742", nombres: "PAREDES BARBOZA LEYDI GLADISBETH", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75983540", nombres: "MENDOZA ALVARADO CINDY THALIA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75493573", nombres: "COMECA CARRASCO GINA STEFANY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75422325", nombres: "MASGO VENTURA MICAELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73759544", nombres: "BUSTOS RUIZ KEYSSI STEFANI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60322167", nombres: "DÍAZ RAMOS MARÍA MERLI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73232436", nombres: "FIERRO GOICOCHEA EDWIN JOSE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73353077", nombres: "CHAVEZ RABANAL JHEAN FRANCIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71994410", nombres: "ILIQUÍN VARGAS CÉSAR DANIEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07760465", nombres: "MIGUEL MACEDO BACA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76661426", nombres: "CARO GUIVIN DARLIN LLEICER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73413887", nombres: "IDROGO CHUQUIZUTA BRENDA ALEXANDRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71521405", nombres: "CARDOZO HUAMAN MARCIA ALEJANDRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75348322", nombres: "RIOJA AYAY LUZ YERLY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76522362", nombres: "ROJAS LOPEZ MARYCRUZ CIELO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71918577", nombres: "QUISPE BURGA JOSEPH PAUL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72515311", nombres: "VILCHEZ TUESTA JUAN MANUEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60017138", nombres: "LOPEZ VALER YHAMILET STEFHANNY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75900274", nombres: "MAS CUIPAL JACKELINE JIMENA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74372627", nombres: "FERNANDEZ GUIMAC CHELCIE JEMIMA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73698514", nombres: "GARCIA LÓPEZ MARIELITA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71650569", nombres: "CIEZA TARRILLO ROBI JHUNIOR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73642604", nombres: "RAMOS BARRIOS JUNIOR DAVID", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73695197", nombres: "HUAMAN HUAMAN ANDERLI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71539882", nombres: "ALBERCA MONTENEGRO ALBERT MATIAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73425107", nombres: "VERA ARTIAGA, ADRIANA LORENA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "43873968", nombres: "JUAN LUIS IBARRA GUTIERREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74620488", nombres: "HERNANDEZ GUERRERO JHON ROBERT", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73621604", nombres: "ESTELA VASQUEZ CECILA YHOMARY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72447667", nombres: "ALVARO JUNIOR OBLITAS SALAZAR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71548137", nombres: "MANUEL SEBASTIAN GARCÍA URRUTIA OLIVERA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72200767", nombres: "JEANCARLO GELDRES VÁSQUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60155941", nombres: "ROJAS DIAZ MARY CIELO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75577861", nombres: "ULLILEN GOÑAS HEIDY LLOLEISY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72086955", nombres: "MELENDREZ CARRASCO ARNIE AARON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73933778", nombres: "ZABALETA COLLANTES JEIDI LALLELI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60778117", nombres: "PESANTES GALLARDO FÁTIMA VANESSA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72894129", nombres: "TUNJAR CASTRO, FIORELA MARILYN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73871811", nombres: "VASQUEZ GONZALES LUIS ORLANDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71582529", nombres: "VILLANUEVA ROJAS ALVARO DANIEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73441875", nombres: "LLANOS GOÑAS MAXS ANTHONY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76148212", nombres: "GALLARDO SOTO YACSON YANDED", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73610883", nombres: "MARIN SANCHEZ JHEFERSON NOEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74952467", nombres: "ALVA CARRION GIANELLA MABEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70911276", nombres: "AREVALO FERNANDEZ ELSI JHOANI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71006042", nombres: "CASTRO BARBOZA YHEYSON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74632346", nombres: "CASTRO CRUZ RODNY GUZMAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72631510", nombres: "CHAVEZ CARRANZA BECKHAM JUNIOR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71251744", nombres: "DELGADO DELGADO SAYRA FIORELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73210229", nombres: "DIAZ CHAMBA HEYDI MARIELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76002250", nombres: "GUEVARA AGUILAR JHERLY JHOANY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76728577", nombres: "HUAMAN BERNILLA FELIPE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73602560", nombres: "HUAMAN CHAVEZ MERALITH", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75144848", nombres: "IDROGO JULON MARCELO IVAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76040821", nombres: "LLATAS VASQUEZ JHON ANDERSON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75075509", nombres: "PISCO TELLO JOSE MANUEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72961253", nombres: "RIVERA AGUIRRE CRISTINA NICOL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71129538", nombres: "SALDAÑA VASQUEZ CARLOS YAGO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60742605", nombres: "VASQUEZ GUERRERO DARWIN DEYVIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71581597", nombres: "VASQUEZ SANCHEZ KAREN SARAI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "33430187", nombres: "POEMAPE OYANGUREN CARLOS RAUL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "43591102", nombres: "DE RUTTE GONZALEZ JEAN PETER EDUARDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "20116931", nombres: "DINA SUSANA PAUCAR CONDOR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "47088095", nombres: "VASQUEZ JORDAN MABEL JHULIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75787812", nombres: "WILLIAM CHAVEZ ESPINOZA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71640881", nombres: "LUIS ESMIT MORI COMECA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60209742", nombres: "PORTOCARRERO DELGADO GLEYMER ISAMAR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75230939", nombres: "GUEVARA CHUQUIBALA RICHAR JOSUE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75334478", nombres: "CHÁVEZ MELENDEZ FABIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77569862", nombres: "CHUQUIZUTA DAZA DIANA JULISSA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60730276", nombres: "TELLO VILLACREZ CESAR ALEXHANDER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73701004", nombres: "SOLANO SAUCEDO KELY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72978784", nombres: "CHERO TAFUR MARIA ALEJANDRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71242440", nombres: "ASBEL ARELÍ TAKAYAMA GUERRERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "10536464", nombres: "JOSÉ AUDAR HERRERA JARA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07183532", nombres: "EDWIN MARCEL PECCIO CHAVESTA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75802771", nombres: "PEÑA TABOADA MIXAEL EDINSON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75025327", nombres: "VILLACORTA CRUZADO MIQUEAS AARON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71788204", nombres: "DÍAZ LÓPEZ LESTER ALFONSO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74448722", nombres: "ZAVALETA OCAMPO FLORA BERNIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "46421205", nombres: "JONNATHAN CALIXTO VILLACORTA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72637735", nombres: "JUAN ALFONSO SAAVEDRA LÓPEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72197444", nombres: "ANA LUCÍA MONTENEGRO CASTRO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "22520314", nombres: "JEDUTUM BLAS MORA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "23168450", nombres: "DORALIZA ELVIRA SORIA IBAZETA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "22510949", nombres: "MARIA YSABEL CALDAS ORNETA ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "22999935", nombres: "DENNIS MARWIN PEREYRA DIAZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "22419770", nombres: "ROGER ARMANDO BOCANEGRA ARANDA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08244753", nombres: "JOSÉ ANTONIO TEJADA QUINTEROS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09996030", nombres: "JULIO GRISSOM ÁVILA TAMARA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73711651", nombres: "TERRONES MARIN CYNTIA YENIFER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77425825", nombres: "CUEVA IPARRAGUIRRE MARIBEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71768047", nombres: "SÁNCHEZ PÉREZ LUCERO ALEXANDRA ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76086156", nombres: "YOPLA NOVOA CARLOS FERNANDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73245107", nombres: "HUAMÁN ROJAS EVELIN YOLANDA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72708380", nombres: "LUCANO CHUNQUE DIEGO ARMANDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "06800949", nombres: "ROBERTO DAVID LAVADO ARIZA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71936294", nombres: "MARDY JHULIANA VIN ZUMAETA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "46856178", nombres: "YESSENIA DEL ROCÍO GUTIÉRREZ CHÁVEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60756507", nombres: "LOZANO CHÁVEZ ERICK HERNÁN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71490819", nombres: "ABANTO MUÑOZ JHEYSON MANUEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71966140", nombres: "LÓPEZ ESTELA DEINER OLVER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71858006", nombres: "NUÑEZ VASQUEZ NAYELY RULEICY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74475694", nombres: "GUEVARA COBA DILMER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72492526", nombres: "MARÍA BELÉN MESTA BARBOZA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76764969", nombres: "VARGAS RODRÍGUEZ DEYSI MENELI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73103785", nombres: "VÁSQUEZ TERÁN FABRICIO JOSÉ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72433668", nombres: "PAREDES IZQUIERDO JEINER MICHEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75063606", nombres: "GUEVARA VÁSQUEZ SEIR ALEXANDER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75836941", nombres: "NÚÑEZ VÁSQUEZ MARIANELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74832632", nombres: "TERÁN VENTURA PIERE JOMAR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72411905", nombres: "JUAREZ DIAZ DENILSON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71257568", nombres: "AGUILAR RAMIREZ SANDRA LIZETH", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72045377", nombres: "SILVA MATARA YEFERSON LUIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72836988", nombres: "VÁSQUEZ TERRONES DENIS ABELARDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74911248", nombres: "RUIZ BENAVIDES JHAN ALEX", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74637447", nombres: "QUINTANA BENAVIDES JHONATAN OMAR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73136335", nombres: "DILMER JHORDIN ISHPLICO HUARIPATA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75022847", nombres: "ZELADA HUAMAN JUAN ABRAHAM", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60879952", nombres: "CAMACHO QUIROZ REGINA JHULLIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75054060", nombres: "CASTRO COTRINA JHULSY GUADALUPE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72136172", nombres: "AMAMBAL QUISPE KELY LILIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72641166", nombres: "MARIN FERNÁNDEZ EULER LEONARDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60730655", nombres: "CUBAS AYAYPOMA SINTIA BANESSA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77062440", nombres: "VASQUEZ MEDINA EMMER GIOVANI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75054060", nombres: "CASTRO COTRINA JHULSY GUADALUPE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72112568", nombres: "LEIVA IZQUIERDO STEPHANY YAZMIN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08676932", nombres: "RAQUEL VERÓNICA DE LA CRUZ CACHAY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72536460", nombres: "MARÍN TAPIA JHAN BREYNER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75592455", nombres: "ABANTO HUAMAN NESTOR JOSE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41235760", nombres: "NUÑEZ TERRONES JORGE EDUARDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07856420", nombres: "FAUSTINO VICTOR CUEVA QUISPE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74961078", nombres: "GUEVARA RAFAEL EVER LUIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77678038", nombres: "CUEVA CORTEZ ROSMELL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74753461", nombres: "ALICIA GIANELLA HUATAY RONCAL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73696417", nombres: "HERRERA HUAMAN JHAN FRANCO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71966139", nombres: "LÓPEZ ESTELA MIRIAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75266258", nombres: "MUÑOZ TINOCO HUBILSER DESLIN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71980252", nombres: "GONZALES VILCHEZ PABLO RAFAEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73147342", nombres: "PAJARES FLORES ANAÍS PATRICIA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72170063", nombres: "GUEVARA QUIROZ MARÍA DEL CIELO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74885578", nombres: "JULCAMORO LLANOS YESSICA YAMIRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76546641", nombres: "QUIROZ CORTEZ ALEXA FABIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74840720", nombres: "PEREZ DIAZ DAYANNA MADELEINE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72133721", nombres: "VIGO DILAS LISBETH", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76437465", nombres: "GALLARDO AGURTO YERALDO JOSUÉ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74079538", nombres: "CALUA LÓPEZ MARK CRHISTOPHER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71875459", nombres: "PUSMA GARCIA IDELSA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72426402", nombres: "CAMPOS EDQUEN EDWIN ROSMEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75884471", nombres: "RAMIREZ AGURTO MARITA DANIELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60424572", nombres: "CHAVEZ VERA JHOANN ORLANDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74074342", nombres: "MORENO CARAHUATAY NILTON EFRAIN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75943482", nombres: "CHAVEZ MORALES JUAN EDGAR EGBERTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21101457", nombres: "JULIO LUIS SORIA MOSQUERA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09976416", nombres: "HAYDEE MONICA MAMANI RIOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75986809", nombres: "ANA EDITH ROJAS VASQUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "45140038", nombres: "LAUREL SILVA GABRIEL AGUSTIN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73111812", nombres: "ADRIAN MAURICIO CAYOTOPA LATORRE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75885655", nombres: "CARMONA ALCANTARA LUZ ANGELICA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75526961", nombres: "CASTILLO MANAYALLE PERCY FABIAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74690311", nombres: "TARRILLO VASQUEZ MERLIT LISETH", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75021818", nombres: "ZAMBRANO CHILON FRANKLIN HENRY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71226039", nombres: "SUAREZ MALCA YONATHAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71797198", nombres: "COJAL GAMBOA JUAN CARLOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71330533", nombres: "SAAVEDRA ALVA DIEGO GABRIEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75621675", nombres: "BUSTAMANTE BUSTAMANTE GIMENA DE LOS ÁNGELES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60217420", nombres: "ORDOÑEZ RODAS LUIS JONATHAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77055045", nombres: "FLORES SANCHEZ HENNRY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71381815", nombres: "ABANTO GUILLÉN DIEGO FABRICIO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72437904", nombres: "MACHUCA GOICOCHEA VIVIANA ISABEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72475738", nombres: "CERDÁN VÁSQUEZ RUTH FIORELA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72486875", nombres: "VALDIVIA DIAZ ERIKA MARIBEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "61275962", nombres: "MICHA GOICOCHEA YESICA ISABEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71795829", nombres: "ISPILCO LOPEZ WILMER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76761188", nombres: "AQUINO QUISPE HAYDELI ESTHER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75484005", nombres: "RAMOS TARRILLO LUIS IVÁN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "26702348", nombres: "JIMÉNEZ RÍOS CARLOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75318860", nombres: "CHILÓN SEGURA EYDAN ALDAIR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71975531", nombres: "GAITÁN MARCELO GINO JAIRO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60222251", nombres: "AGUILAR CARUAJULCA CLEVER OMAR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72936105", nombres: "CARRASCO VASQUEZ JONATAN OBED", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75148667", nombres: "CHUQUILIN GAMBOA VÍCTOR ALEXANDER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74931830", nombres: "PÉREZ CHUQUILÍN SANDRA MAYTÉ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "03649766", nombres: "GUILLERMO FLORES COBEÑAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74558426", nombres: "FUSTAMANTE SÁNCHEZ EMERSON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74461115", nombres: "MAIKEL IMANOL FRIAS MOZOMBITE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74464466", nombres: "DÍAZ LEYVA EDIVER ROMARIO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71415005", nombres: "ARAUJO MARÍN WILLIAM RAFAEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77064586", nombres: "PUERTA LINARES WENINGER JOEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71593962", nombres: "ALAYA SANCHEZ ANALI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73702762", nombres: "RUBIO TIRADO ROSA ADELI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73250242", nombres: "HUAYAN JUAREZ KEND STEVEN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73802211", nombres: "VILLAR MINCHÁN LEYDY MALENA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74558405", nombres: "HUAMÁN VÁZQUEZ SANDRO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74961266", nombres: "ANGEL ANTONIO ESPINOZA GUERRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77077082", nombres: "ARIAS CULQUE STEPHANIE NAYELY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "06010272", nombres: "SILVA ZAPATA OSWALDO INDALECIO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70866580", nombres: "EVA LUNA CALLE BRICEÑO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76779925", nombres: "AZULA CHAYSA ANGIE PAOLA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74880669", nombres: "ATALAYA QUILICHE LUZ EVITA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "22077429", nombres: "LOPEZ GAVANCHO JHONNY ENRIQUE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21577919", nombres: "VÍCTOR OSCAR MOYANO MUSTTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21527063", nombres: "NAVARRO GUERRA BELINDA MARLENI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21415985", nombres: "ARMAS TORRES RICARDO ALBERTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71702236", nombres: "FRANCO DAMIÁN LOZANO VILCA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75874399", nombres: "SAIRA MARGOTH ABAD YZQUIERDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72326529", nombres: "XIOMARA CARRANZA ROMERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74024938", nombres: "DANIELA ASPILLAGA VÁSQUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71637753", nombres: "MARÍA TORO LÓPEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77040084", nombres: "JESUS ALONSO PALACIOS CABREJOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75508282", nombres: "JOSÉ GUSTAVO PISFIL TULLUME", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76063905", nombres: "JULIO CESAR CLAVO SALAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75725275", nombres: "CHRISTIAN MARTIN LABAN FACUNDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07629541", nombres: "RUBEN SEVERO ROJAS DE LA CRUZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74298493", nombres: "BAUTISTA YGNACIO JHOAN MANUEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "06087923", nombres: "HEBER CELSO OLIVA ZELADA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72849036", nombres: "DANIELA FERNANDA RODRIGUEZ CASTILLO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "40788172", nombres: "CAMPOS MORALES SEGUNDO EMILIO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "46382318", nombres: "MENDOZA PAREDES HERMÁN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76398077", nombres: "BECERRA TACILLA KENYI JHEFERSON", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41192516", nombres: "MIGUEL ÁNGEL HERRERA RODRÍGUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08145362", nombres: "RAÚL FUENTES REYNOSO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74053505", nombres: "MARIA NICOLE VILCA ACERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09281407", nombres: "DAVID ALEJANDRO REYNAGA ROJAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "32868069", nombres: "LILIA EDITH HUAMAN CARRASCO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70203609", nombres: "CHICLOTE CHUCCHUCAN DEYSI MARIBEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74069039", nombres: "TACILLA GONZALES MILAGROS MISHEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74804083", nombres: "RAMÍREZ JULCAMORO ANA CRISTINA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70199587", nombres: "CABANILLAS CASTAÑEDA RAÚL ANTONIO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74832612", nombres: "GUEVARA MENDOZA FIORELA JHANAIRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71879347", nombres: "JHON ANTONY NEYRA CRUZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75874875", nombres: "ERIK JAIR RODRIGUEZ CIEZA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73335723", nombres: "MARBIL YAEL GUERRERO IRENE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "06905509", nombres: "MARCO ANTONIO VILLASANTE SÁNCHEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73531597", nombres: "GUERRERO YARLEQUE KELLY JESÚS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73131319", nombres: "HIDALGO MARQUEZ GERARDO ROBERANDY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70514905", nombres: "SEMINARIO TIMOTEO YESENIA JOCINEY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73536159", nombres: "RUIZ SAAVEDRA YERSON ELBER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74901888", nombres: "NICOLL ANAÍS SILVA JUÁREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76054449", nombres: "GUERRERO MARTÍNEZ LEIDY IVANNY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74992517", nombres: "MARIBELLA SALECSI ROMERO HURTADO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76879214", nombres: "RODRIGUEZ FERNANDEZ LILIANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74040547", nombres: "ARCE CABRERA LARRY JERICO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71971345", nombres: "GUEVARA LOPEZ LESLY YARACELI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "26634295", nombres: "SOTO SÁNCHEZ ELIO ROGER", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "01159874", nombres: "CARMEN TEODORO CÁRDENAS ALAYO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75824507", nombres: "JEFFERSON RAUL MEZA RODRÍGUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74131372", nombres: "SHANIA ABRIL AHUMADA ARMAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60051340", nombres: "LEONEL ALEXANDER CHUMACERO CORDOVA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74492488", nombres: "SILVA ANAYA SARA EVELYN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74590756", nombres: "RAUL OLIVO SANDOVAL SANCHEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71981144", nombres: "KAREN DAJHANA CIEZA MEDINA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75850450", nombres: "GUICELA YAQUELIN DÍAZ COTRINA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "10623927", nombres: "CHRISTIAM ADAM QUIROZ VARGAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73393274", nombres: "JARRY ALEXANDER PERALTA SEMPERTEGUI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74705947", nombres: "ESTRELLITA MARIBEL JIMENEZ DOMINGUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "10805941", nombres: "GERMAN EUGENIO SALAZAR SANTOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70636511", nombres: "MACHARÉ RAMOS MARÍA LUCERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75108455", nombres: "VALENCIA MOROCHO JOEL DANILO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "45705161", nombres: "VANESSA JACQUELIN HUAMANI ROJAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41075391", nombres: "EVELYN JUDITH DOMÍNGUEZ GUTIÉRREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09011210", nombres: "ROJAS CUBAS JUAN CARLOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09296005", nombres: "MOROTE CANALES IVÁN AMILCAR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76428367", nombres: "CARLOS IVAN PULACHE ORDOÑEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "25566632", nombres: "ORE ZEVALLOS VICTOR ALEXIS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "25710988", nombres: "RAÚL MARCOS LÓPEZ GAMARRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76789756", nombres: "LLICO CHUNQUE ERIKA LISSET", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "02141321", nombres: "ANDRÉS LEONIDAS PAYÉ COLQUEHUANCA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "42060541", nombres: "CRUZADO GARCIA MILTON YONEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71046889", nombres: "KONIK WINIFERD SALINAS AZAÑERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72132378", nombres: "CHUNQUE SILVA JESSICA MARIBEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72965327", nombres: "ESCOBAR SANGAY ORLANDO MISAEL", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72965328", nombres: "ESCOBAR SANGAY GABRIEL SANTANA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "00094842", nombres: "EDWIN MILLAN PARIONA CABRERA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77567918", nombres: "ABRIL MALORY CASTRO PURIZACA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73118322", nombres: "ARIANA DEL CARMEN NAVARRO FUENTES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73415924", nombres: "JHAMPIERE JHERENMY HUAMAN TORRES", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70207730", nombres: "CHUQUIPOMA SALDAÑA JULIO RICARDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "10363085", nombres: "ELIZABETH CONSUELO LÓPEZ GUTIÉRREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "20054795", nombres: "CARMEN MARÍA RIVERA OLLERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "17905184", nombres: "RAMIRO EULOGIO ZAVALETA MÉNDEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41532323", nombres: "ALEXANDER IVAN ZAVALETA NUÑEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74433615", nombres: "BARBOZA MONDRAGÓN JAMES JAHIR", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07311677", nombres: "MIGUEL CRUZ LABRIN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07839328", nombres: "JUAN PLÁCIDO BILBAO SIERRALTA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71573682", nombres: "CARLOS MARX CERQUÍN CHILÓN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "76832995", nombres: "DEYSI MARGOT GUEVARA DÁVILA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "40340910", nombres: "ARANA FUSTAMANTE EDWING", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72553418", nombres: "DARNER HUBERT SÁNCHEZ DÍAZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60208952", nombres: "JHONATAN KENNEDY ATALAYA CERCADO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73047055", nombres: "GALÁN VALIENTE JOSSEN EDDÚ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "40299530", nombres: "WILMER ROSEBEL VASQUEZ CUBAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "43088515", nombres: "TATIANA TAISBEL SANCHEZ VARGAS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70445381", nombres: "JOSÉ MANUEL VALDERRAMA GARAY", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "60448407", nombres: "JHEYSON ABANTO CABELLOS", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71737956", nombres: "CHRISTOPHER CARLOS AGUILAR CRUZADO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "77333361", nombres: "MARÍA JHOSELIN PRIETO CARRASCO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "06054278", nombres: "ROGER VASQUEZ CHICHIPE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73828079", nombres: "LUCERO CRISTELL CANCHANYA ARTEAGA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "17813650", nombres: "GASTÓN ELEODORO MAGUIÑA RODRIGUEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "41905212", nombres: "MODERLI MAS DELGADO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08583595", nombres: "REYNA HILDA AGRAMONTE VERAMENDI", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "06853993", nombres: "DIGNA JUBENCIA CORDOVA DIAZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "42904573", nombres: "DIEGO ENRIQUE SUAREZ RAMIREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "72624687", nombres: "ANNY LISSETH REQUEJO ROMAN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "26718001", nombres: "ROBERTO VIDAL MONTERO PALACIOS ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "18211360", nombres: "LUIS ALBERTO VIGO LLEMPÉN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "73769067", nombres: "HUGO CÉSAR MORALES CORTEZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08806187", nombres: "FREDY EDGARD VÉLIZ ARAUCO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "18042114", nombres: "MERCANDER FUNDADIR AGUILAR QUISPE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "09349103", nombres: "CARLOS ALFREDO SANCHEZ GUTIERREZ", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08742755", nombres: "LUIS ENRIQUE FUENTES BOBADILLA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "71862155", nombres: "LUIS FERNANDO DANIEL CHÁVEZ ZEGARRA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "02617748", nombres: "GLORIA CALERO ROMERO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75427493", nombres: "KYM SAMANTHA TICONA ESPINOZA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "31033024", nombres: "HELGA STEFFEN AGUIRRE", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "74221547", nombres: "ROSITA MILAGROS RODRIGUEZ IZQUIERDO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "21010733", nombres: "FABIOLA CRUZ NAVARRO SOTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07289011", nombres: "VICTOR RAÚL SAUSA POTOZEN", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "25488129", nombres: "ELOISA SAIDA ALVA PRADO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "75136509", nombres: "ÁNGEL FABIÁN AGUIRRE BAUTISTA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70017130", nombres: "RAÚL DONATO TEJADA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "22405065", nombres: "LIZARDO CAICEDO DAVILA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "70399154", nombres: "DAVID AVILA ARAUCO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "08184286", nombres: "CARLOS GUSTAVO MORI CARO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "20028605", nombres: "MARITZA LOURDES CASTILLO LARA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "44040675", nombres: "ROBERTH LOAYZA MEZA", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "07465846 ", nombres: "JUAN CARLOS GALVÁN RETTO", certificado:"CONSTANCIA CONEP24.pdf" },
    { dni: "46901654", nombres: "FLOR MARIANA RAMÍREZ ROSARIO", certificado:"CERTIFICADO SMARTPeru setiembre.pdf" },
    { dni: "71396636", nombres: "MARY KATHERINE DURÁN AGUIRRE", certificado:"CERTIFICADO SMARTPeru setiembre.pdf" },
    { dni: "40717853", nombres: "TERESA RODRIGO VASQUEZ", certificado:"CERTIFICADO SMARTPeru setiembre.pdf" },
    { dni: "47042298", nombres: "MIRIAN ARELY SÁNCHEZ CHÁVEZ", certificado:"CERTIFICADO SMARTPeru setiembre.pdf" },
    { dni: "44278145", nombres: "LILIAN ESTHER CASTAÑEDA VILLAVICENCIO", certificado:"CERTIFICADO SMARTPerú Nutrición.pdf" },
    { dni: "71338215", nombres: "MARILYN YARALDI VILLANUEVA ESPEJO", certificado:"reposteria.pdf" },
    { dni: "42372968", nombres: "SARITA HAYDÉE REYES BENITES", certificado:"reposteria.pdf" },
    { dni: "44382616", nombres: "ELICIA RAMIREZ CUSTODIO", certificado:"reposteria.pdf" },
    { dni: "73178367", nombres: "ERICA ABIGAIL CRUZ RODRIGUEZ ", certificado:"Certificado AGO.pdf" },
    { dni: "46273698", nombres: "MARGOT PONCE DE LA CRUZ", certificado:"Certificado AGO.pdf" },
    { dni: "47510951", nombres: "NEYDA  MILENY TORIBIO BRICEÑO", certificado:"pescados_mariscos.pdf" },
    { dni: "42756199", nombres: "MARTHA BETZABETH RODRÍGUEZ DÍAZ", certificado:"pescados_mariscos.pdf" },
    { dni: "71804505", nombres: "NANCY ZULEMA ALVA TIRADO", certificado:"reposteria.pdf" },
    { dni: "71855065", nombres: "ERICK JHORDAN TORRES QUISPE", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "75148667", nombres: "VÍCTOR ALEXANDER CHUQUILIN GAMBOA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "72622889", nombres: "ESLY LISETH RODAS AQUINO", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "73670203", nombres: "KATHERINE MARICIELO BURGA RIVERA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "70248637", nombres: "JORGE LUIS, ARIAS SALAS", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "73535301", nombres: "VÍCTOR HUGO, VILLEGAS DIAZ", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71374863", nombres: "VALDEZ YOPLA, SAMUEL YOJANIS", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71447836", nombres: "ARRELUCEA ARIAS SAMANTHA MAXIMINA YOLANDA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71981089", nombres: "FLÓREZ CHÁVEZ SAMMY RUBÍ", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71460354", nombres: "PEREZ VASQUEZ MARIA YULISA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "72077478", nombres: "RUTH MEDALID HOLGADO VERA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "74697028", nombres: "MILAGROS LIZET GARCÉS QUISPE", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "76814972", nombres: "CAROLAY LEYDY LOBATO CALUA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "70203609", nombres: "CHICLOTE CHUCCHUCAN DEYSI MARIBEL", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "75900456", nombres: "ANAPAULA DÍAZ MONTOYA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "40776296", nombres: "CHAVEZ SALCEDO MARIBEL", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "70495770", nombres: "MASIEL GERALDINE GAMBOA JIMÉNEZ", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71257572", nombres: "HUAMÁN MURGA JOEL", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "75452472", nombres: "VIDARTE SÁNCHEZ MILAGROS", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71374863", nombres: "VALDEZ YOPLA, SAMUEL YOJANIS", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "42359786", nombres: "ÓSCAR ORTIZ REGALADO", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "74475694", nombres: "DILMER GUEVARA COBA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71967920", nombres: "ORLANDO ACUÑA TINOCO", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "76344394", nombres: "CELIS SOLÓN EDITHA FIORELA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71345597", nombres: "LUZ KARINA MONZON JARA", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "00002024", nombres: "LICELY YONALY MANOSALVA CAMPOS", certificado:"DIPLOMADO EN GP.pdf" },
    { dni: "71228184", nombres: "DIANA ELVIRA ALIAGA GALLARDO", certificado:"AI-BVL.pdf" },
    { dni: "73186760", nombres: "MARILÚ ISAMAR RIOJAS BURGA", certificado:"AI-BVL.pdf" },
    { dni: "73122192", nombres: "GUADALUPE GABRIELA GARCÍA CABRERA", certificado:"AI-BVL.pdf" },
    { dni: "45475919", nombres: "ROBERTO CARLOS ARMAS VÁSQUEZ", certificado:"Certificado SMART Pescados y Mariscos JULIO.pdf" },
    { dni: "42057264", nombres: "EDUARDO CALDERÓN LLANOS", certificado:"Certificado SMART Pescados y Mariscos JULIO.pdf" },
    { dni: "71767989", nombres: "ERICKA JAZMINA BELTRÁN CORTEZ", certificado:"Certificado SMART Pescados y Mariscos JULIO.pdf" },
    { dni: "71226825", nombres: "FREDDY ORLANDO JULCA TORRES", certificado:"Certificado SMART Platos a la Carta.pdf" },
    { dni: "74439475", nombres: "ÁNGEL MAYCOL PRÍNCIPE JARA", certificado:"Certificado SMART Platos a la Carta.pdf" },
    { dni: "75088745", nombres: "RODRÍGUEZ CABELLOS YHENY YASMIN", certificado:"AI-BVL.pdf" },
    { dni: "73946809", nombres: "DEYSI FLORES ROJAS", certificado:"PANADERIA.pdf" },
    { dni: "74439475", nombres: "ÁNGEL MAYCOL PRÍNCIPE JARA", certificado:"PANADERIA.pdf" },
    { dni: "70667738", nombres: "MARGARITA ISELA URTECHO ALVARADO", certificado:"PANADERIA.pdf" },
    { dni: "71758539", nombres: "EVELYN MARILUZ CISNEROS QUISPE", certificado:"AI-BVL.pdf" },
    { dni: "70174983", nombres: "DIEGO ANTONIO ESPINO VEJARANO", certificado:"AI-BVL.pdf" },
    { dni: "74904159", nombres: "LOZANO COTRINA FRANK JEANPIERRE", certificado:"AI-BVL.pdf" },
    { dni: "00002025", nombres: "LICELY YONALY MANOSALVA CAMPOS", certificado:"AI-BVL.pdf" },
    { dni: "45372353", nombres: "ROSARIO DEL PILAR HEREDIA OLIVERA", certificado:"AI-BVL.pdf" },
    { dni: "73512520", nombres: "GABRIELA KATHERINE MICHILOT HUACHILLO", certificado:"AI-BVL.pdf" },
    { dni: "45694656", nombres: "KATTY GISSELA REYES VELÁSQUEZ", certificado:"AI-BVL.pdf" },
    { dni: "72910613", nombres: "BURGA DELGADO CRISTIAN MAYCOL", certificado:"AI-BVL.pdf" },
    { dni: "17860294", nombres: "VICTORIA HAYDEÉ VEJARANO GARCÍA", certificado:"AI-BVL.pdf" },
    { dni: "72772441", nombres: "JHENNY LISBETH VÁSQUEZ HUAMAN", certificado:"AI-BVL.pdf" },
    { dni: "71480130", nombres: "CORACY MINERVA SAENZ ANTONIO", certificado:"AI-BVL.pdf" },
    { dni: "72513092", nombres: "SANDRA MILAGROS PASTOR IZQUIERDO", certificado:"AI-BVL.pdf" },
    { dni: "73102690", nombres: "MELANI NICOL RODRIGUEZ JAIMES", certificado:"AI-BVL.pdf" },
    { dni: "72214050", nombres: "SOFÍA YENNIFER MORALES SÁNCHEZ", certificado:"AI-BVL.pdf" },
    { dni: "70200660", nombres: "SILVIA MERCEDES CUBA FERNANDEZ", certificado:"AI-BVL.pdf" },
    { dni: "70134421", nombres: "ADELI GRIMANESA MARIN ESPINOLA", certificado:"AI-BVL.pdf" },
    { dni: "72740259", nombres: "NELI ALEJANDRINA QUIROZ BADA", certificado:"reposteria.pdf" },
    { dni: "74292387", nombres: "CÉSAR PERCY SANTOS TORRES", certificado:"pescados_mariscos.pdf" },
    { dni: "71338223", nombres: "NILDA JULISSA TORIBIO BRICEÑO", certificado:"bartender.pdf" },
    { dni: "46767121", nombres: "DIANE EMELYT VALDEZ MONSEFÚ", certificado:"bartender.pdf" },
    { dni: "46901654", nombres: "FLOR MARIANA RAMÍREZ ROSARIO", certificado:"PANADERIA.pdf" },
    { dni: "41716165", nombres: "SANDERS WIDMARK SÁNCHEZ CONTRERAS", certificado:"bartender.pdf" },
    { dni: "74292387", nombres: "CÉSAR PERCY SANTOS TORRES", certificado:"bartender.pdf" },
    ];
